name: Auto Tag
on:
  pull_request:
    types:
      - closed
    branches:
      - main
concurrency: production
jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: '0'
      - name: Tag Dry Run
        id: taggerDryRun
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DRY_RUN: true
      - name: Tags
        run: |
          echo "The next tag version will be: ${{ steps.taggerDryRun.outputs.new_tag }}" \
          echo "The current tag is: ${{ steps.taggerDryRun.outputs.tag }}" \
          echo "The version increment was: ${{ steps.taggerDryRun.outputs.part }}"      
      - name: Tag Pre-release
        id: taggerFinal
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          PRERELEASE: true
